### ISSUE TITLE
Question on how to pass pretrained parameters to a self-defined optimizer

### ISSUE THREAD

**Issue by leonleeldc** [pytorch/fairseq#3225]
## 🐛 Bug

Hi, group,

I am new to fairseq. I encounter a problem in deploying it. In my project, I have defined a new optimizer. I know the file should be put into fairseq/optimu/my_optimizer.py.

But the problem is that in my_optimizer.py, I have a new paprameter, as,  pretrain_params=None.

We need to computer differences between pretrain_params and params.

My question is how I can pass pretrain_params to this optimizer. 
In huggingface, I can do the following, 
optimizer_grouped_parameters = [
{
"params": [p for n, p in model.named_parameters() if
not any(nd in n for nd in no_decay) and args.model_type in n],
"weight_decay": args.weight_decay,
"anneal_w": args.recadam_anneal_w,
"pretrain_params": [p_p for p_n, p_p in pretrained_model.named_parameters() if
not any(nd in p_n for nd in no_decay) and args.model_type in p_n]
}, ...,]

optimizer = my_optimizerr(optimizer_grouped_parameters, lr=args.learning_rate, eps=args.adam_epsilon,
anneal_fun=args.recadam_anneal_fun, anneal_k=args.recadam_anneal_k,
anneal_t0=args.recadam_anneal_t0, pretrain_cof=args.recadam_pretrain_cof)

Not sure where fairseq can do this? I tried  to do this in fairseq/trainer.py. But not clear where we can load the pretrained_checkpoint.pt and pass it where for my_optimizer.py to consume. 

May you guys help with this? Thanks in advance,

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): linux
 - How you installed fairseq (`pip`, source): I am using the latest whole fairseq source package 
 - Build command you used (if compiling from source): pip install editable .
 - Python version: 3.6
 - CUDA/cuDNN version: cuda 9
 - GPU models and configuration: v100
 - Any other relevant information:

**Comment by alexeib** [comment]
you can try using this:

https://github.com/pytorch/fairseq/blob/master/fairseq/optim/composite.py

you would have to mark parameters with their group name in your model

something like this:

```python
for p in self.submodel.parameters():
    p.param_group = "submodel"
```

then you can set up a composite config with different optimizer parameters, something like this:

```yaml
optimizer:
  _name: composite
  groups:
    default:
      lr: [0.0004]
      optimizer:
        _name: adam
        adam_betas: [0.5,0.98]
        adam_eps: 1e-06
        weight_decay: 0
      lr_scheduler:
        _name: fixed
        warmup_updates: 0
    submodel:
      lr: [ 0.0005 ]
      optimizer:
        _name: adam
        adam_betas: [0.5,0.98]
        adam_eps: 1e-06
        weight_decay: 0.0001
      lr_scheduler:
        _name: fixed
        warmup_updates: 0

lr_scheduler: pass_through
```
