### ISSUE TITLE
Unable to train/eval a ASR model on LibriSpeech

### ISSUE THREAD

**Issue by Atla11nTa** [pytorch/fairseq#3501]
## ❓ Questions and Help

When I follow fairseq/examples/speech_to_text/docs/librispeech_example.md to train a ASR model on LibriSpeech, the following error occurred:
 
`File "/fairseq/models/speech_to_text/s2t_transformer.py", line 337, in forward
    if self.num_updates < self.encoder_freezing_updates:
TypeError: '<' not supported between instances of 'int' and 'NoneType'`

1. I find a similar issue: #3457 , and following his suggestion,  I checked fairseq/models/fairseq_model.py, but this file had been fixed in lastest commit, it still shows the same error message.

2. Following the error message, I check `s2t_transformer.py`,  I think the parameter `encoder_freezing_updates` should be given in the config.yaml.  The config file `config.yaml` is generated automatically during data preprocessing. is it incomplete?  If it incomplete, anyone can show a complete one?
```
**config.yaml**

bpe_tokenizer:
  bpe: sentencepiece
  sentencepiece_model: /home/zhuriyong/wanchengyi/fair_librispeech_preprocessed_data/spm_unigram10000.model
input_channels: 1
input_feat_per_channel: 80
sampling_alpha: 1.0
specaugment:
  freq_mask_F: 27
  freq_mask_N: 2
  time_mask_N: 2
  time_mask_T: 100
  time_mask_p: 1.0
  time_wrap_W: 0
transforms:
  '*':
  - utterance_cmvn
  _train:
  - utterance_cmvn
  - specaugment
vocab_filename: spm_unigram10000.txt
```
3. Finally, I give the parameter a default value 1 (None, before), and ran the training command again, nothing error shows this time.

```
**/fairseq/models/speech_to_text/s2t_transformer.py, line 204.**

        parser.add_argument(
            '--encoder-freezing-updates',
            default=1,
            type=int,
            metavar='N',
            help='freeze encoder for first N updates'
        )
```
4. what's the parameter `encoder-freezing-updates` mean?  what's the reasonale value?
