### ISSUE TITLE
wav2vec2 finetuning is broken due to missing parameters in config

### ISSUE THREAD

**Issue by harveenchadha** [pytorch/fairseq#3511]
I am trying to train on new fairseq version where I encountered this error.

There are fields that are missing in fairseq config provided for finetuning.

For example:

In common section of [config](https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/config/finetuning/base_10h.yaml) we have:

```
common:
    fp16: true
    log_format: json
    log_interval: 200
```

but when I start finetuning it keeps on saying parameters are missing. So I try to add parameters one by one and the final config for common section looks like:

```
common:
    no_progress_bar: false
    log_interval: 500
    log_format: json
    tensorboard_logdir: 
    wandb_project: 
    azureml_logging: false
    seed: 2337
    cpu: false
    tpu: false
    bf16: false
    memory_efficient_bf16: false
    fp16: true
    memory_efficient_fp16: false
    fp16_no_flatten_grads: false
    fp16_init_scale: 128
    fp16_scale_window: 
    fp16_scale_tolerance: 0.0
    min_loss_scale: 0.0001
    threshold_loss_scale: 
    user_dir: 
    empty_cache_freq: 0
    all_gather_list_size: 16384
    model_parallel_size: 1
    quantization_config_path: 
    profile: false
    reset_logging: false
    suppress_crashes: false
    use_plasma_view: false
    plasma_path: '/tmp/plasma'
```

I want to understand why is this so. Why does all the unspecified parameters initialize themselves.

Similar process I need to do for all the other parts in the config.
