### ISSUE TITLE
Question about quant-noise example

### ISSUE THREAD

**Issue by DongChanS** [pytorch/fairseq#3544]
#### What is your question?

I trained Transformer language model with quant-noise and iterative product quantization.

But the inference time is not reduced.

Why it does? is there any API for quantized model that i didn't know?

#### What have you tried?

I trained quantized model following way

```bash
FAIRSEQ=$1
MODEL_DST=$2

mkdir -p "$MODEL_DST/adaptive_transformer_charlm_quant_v2"

python3 $FAIRSEQ/train.py "$MODEL_DST/decoder/fairseq_charlm_data" \
    --save-dir "$MODEL_DST/adaptive_transformer_charlm_quant_v2" \
    --restore-file "$MODEL_DST/adaptive_transformer_charlm/checkpoint_last.pt" \
    --reset-lr-scheduler --reset-optimizer --reset-meters --reset-dataloader \
    --task language_modeling_with_generation \
    --arch transformer_lm \
    --optimizer=nag \
    --lr=0.0000004 \
    --lr-scheduler=fixed \
    --fp16 \
    --optimizer adam \
    --weight-decay 1e-07 \
    --clip-norm 0.1 \
    --criterion=candidate_penalty_cross_entropy --rank-alpha 1.0 \
    --batch-size 64 \
    --update-freq 1 \
    --tokens-per-sample 256 \
    --seed 42 \
    --sample-break-mode none \
    --skip-invalid-size-inputs-valid-test \
    --shorten-method=truncate \
    --log-format=json --log-interval=100 \
    --save-interval-updates=50000 --keep-interval-updates=10 \
    --quant-noise-pq 0.05 --quant-noise-pq-block-size 8 \
    --max-epoch 12 \
    --quantization-config-path examples/quant_noise/transformer_quantization_config.yaml \
    --ddp-backend=no_c10d --distributed-world-size=2 > $MODEL_DST/adaptive_transformer_charlm_quant_v2/train.quant_noise.log
```

quantization_config file
```yaml

# Number of Centroids for Product Quantization, by default 256 (byte-aligned)
n_centroids:
    Linear:
        key: in_features
        value: {"*": 256}
    Embedding:
        key: embedding_dim
        value: {"*": 256}

# Block Sizes for Product Quantization
# We suggest: 8 for FFN, 4 for ATTN, 4 for embedding projections, 8 for embeddings
block_sizes:
  Linear:
      key: fuzzy_name
      value: {fc: 8, attn: 4, emb: 4}
  Embedding:
      key: fuzzy_name
      value: {emb: 8}

# Layers to Quantize Sequentially
# We suggest: first FFN, then EMB, then ATTN
layers_to_quantize:
    - decoder\.layers\.\d+\.fc[12]
    - decoder\.embed_tokens\.embeddings\.[012]\.[01]
    - decoder\.layers\.\d+\.self_attn\.(k_proj|v_proj|q_proj|out_proj)
```

Then, the size of model is reduced 201MB -> 48MB

but the inference time is not reduced.

I tried the inference by the way.

```python
lm_step_outputs, state.lm_states = self.lm_model.extract_features(
    state.lm_token.to(self.device),
    incremental_state=state.lm_states
)
lm_step_outputs = self.lm_model.output_layer(lm_step_outputs)
lm_step_outputs = lm_step_outputs.squeeze(1).squeeze(0).log_softmax(dim=-1)
```
(self.lm_model : `TransformerDecoder` object in fairseq) 

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 1.0
 - PyTorch Version (e.g., 1.0) : 1.6.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): 
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 
 - Any other relevant information:
